### ISSUE TITLE
iOS simulator crash, Symbol not found: _UnitySendMessage

### ISSUE THREAD

**Issue by axesve** [facebook/facebook-sdk-for-unity#231]
Hello, I am trying to implement facebook SDK into my project. It works fine on android but when I am trying to run a iOS simulator I get this error message.

```
dyld: lazy symbol binding failed: Symbol not found: _UnitySendMessage
  Referenced from: /Users/axel/Library/Developer/CoreSimulator/Devices/1F79ED22-38DF-4F3F-A57E-610C10D865C1/data/Containers/Bundle/Application/665395A1-4223-4ADC-80C5-49647C56113A/pinball.app/pinball
  Expected in: flat namespace

dyld: Symbol not found: _UnitySendMessage
  Referenced from: /Users/axel/Library/Developer/CoreSimulator/Devices/1F79ED22-38DF-4F3F-A57E-610C10D865C1/data/Containers/Bundle/Application/665395A1-4223-4ADC-80C5-49647C56113A/pinball.app/pinball
  Expected in: flat namespace

```

Is there something I've missed?

**Comment by simonbelingar** [comment]
Basically it's a Unity bug so i'm not sure what can be done sdk-vise. Apparently it is fixed in Unity version 2019.2 ...which will be released in xyz time.

https://issuetracker.unity3d.com/issues/ios-unitysendmessage-is-not-working-on-simulator-when-trying-to-login-to-facebooksdk

https://forum.unity.com/threads/symbol-not-found-_unitysendmessage-with-ios-simulator.612682/

**Comment by axesve** [comment]
@simonbelingar Ah I see what a bummer, will this crash affect Apple when reviewing an app aswell?

**Comment by simonbelingar** [comment]
@axesve not that i know of, the fact is that the actual app works just fine. It's simulator bug only as far as i can tell.
