### ISSUE TITLE
7.17.0 caused duplicate AudienceNwtwork

### ISSUE THREAD

**Issue by realluhui** [facebook/facebook-sdk-for-unity#278]
i upgrade my facebook from 7.15.1 to 7.17.0
when i compile my project use xcode, it show error, 

duplicate symbol __Z21fbad_Cocos2DGetGLViewP6UIViewP10objc_class in:
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBAdBridgeCommon.mm.o)
duplicate symbol _fbad_Cocos2DGetGLViewController in:
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBAdBridgeCommon.mm.o)
duplicate symbol _FBSetStoredIconView in:
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeAdBridge.m.o)
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeBannerAdBridge.m.o)
duplicate symbol _FBGetStoredIconView in:
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeAdBridge.m.o)
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeBannerAdBridge.m.o)
duplicate symbol _FBSetStoredCTAView in:
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeAdBridge.m.o)
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeBannerAdBridge.m.o)
duplicate symbol _FBGetStoredCTAView in:
 /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeAdBridge.m.o)
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeBannerAdBridge.m.o)
duplicate symbol _FBAdIconViewStorage in:
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeAdBridge.m.o)
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeBannerAdBridge.m.o)
duplicate symbol _CTAViewStorage in:
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeAdBridge.m.o)
    /Users/sixcube/Desktop/Xcode/Auto/Frameworks/AudienceNetwork/Plugins/iOS/libs/FBAudienceNetwork.framework/FBAudienceNetwork(FBNativeBannerAdBridge.m.o)

but i don't change audinencetwork,  i change facebook sdk to 7.15.1, it work ok,

**Comment by realluhui** [comment]
in 7.17.1 version, the issue still exists

**Comment by dreamolight** [comment]
Starting from 7.17.0, we use cocoapods to pull FB iOS SDK for unity sdk, you might need to delete FB iOS SDK that imported by old unity SDK, could you try deleting all frameworks from Assets/FacebookSDK/Plugins/iOS?

**Comment by realluhui** [comment]
i deleted Assets/FacebookSDK/Plugins/iOS directory, the issue still exist

**Comment by dreamolight** [comment]
@realluhui  could you share a test project with us?

**Comment by giliwerner** [comment]
I get the exact same error after updating the facebook sdk...

**Comment by realluhui** [comment]
@ it's my test project url   https://github.com/realluhui/test_facebook
unity version is 2018.4.0f1
facebook version is 7.17.1
audiencenetwork is 5.2.0
it export xcode project success, when compile use xcode, it show error

**Comment by Apoll0** [comment]
**dreamolight**
> @realluhui could you share a test project or the Podfile of generated project with us?
Here is my generated POD file:
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '10.0'

target 'Unity-iPhone' do
pod 'Bolts', '~> 1.7'
pod 'FBSDKCoreKit', '~> 5.2'
pod 'FBSDKLoginKit', '~> 5.2'
pod 'FBSDKShareKit', '~> 5.2'
pod 'Google-Mobile-Ads-SDK', '~> 7.42.1'
end

```
Assets/FacebookSDK/Plugins/iOS - is empty.
Facebook SDK 7.17.1, Audience 5.4.1. The realluhui's error is still here while compiling by Xcode

**Comment by dreamolight** [comment]
@Apoll0  could you check whether there is multiple FBSDKCoreKit.framework in the generated project? It'd be great if you can share a screenshot of files of the generated project on Xcode.

**Comment by dreamolight** [comment]
Also, @realluhui and @Apoll0 , how did you integrate with audience network SDK? If you integrate audience network manually, you don't need to drag FBSDKCoreKit.framework file into the project as facebook unity sdk has it already.

**Comment by realluhui** [comment]
@dreamolight 

[
![{63088652-7681-4A6E-923D-18DEA4682E5D}](https://user-images.githubusercontent.com/7540485/61433612-55a2c600-a966-11e9-9a30-b1d22d234fd3.png)
](url)

i just find FBSDKCoreKit.framework in Pods Directory

**Comment by armnotstrong** [comment]
Live here, we are encounting with the same issue!

**Comment by Apoll0** [comment]
Audience network and FB sdk ware integrated by unitypackage from the Facebook developer site. Then export to Xcode, build - error. Nothing was added manually. A month or two ago everything was ok, but after upgrading FBSDK & Audience SDK error have appeared.

<img width="267" alt="Screen Shot 2019-07-18 at 09 25 13" src="https://user-images.githubusercontent.com/5494179/61434237-1496bb80-a93e-11e9-959e-98462ed53b5b.png">
<img width="267" alt="Screen Shot 2019-07-18 at 09 25 26" src="https://user-images.githubusercontent.com/5494179/61434243-182a4280-a93e-11e9-9ffd-6c0e1d93a295.png">

**Comment by armnotstrong** [comment]
I am wondering will deleting the FBAudienceNetwork.frame work from lib folder of Unity Project and add it to cocoapods helps? But we don't know which iOS native lib version of FAN for Unity v5.4.1 is using, because the latest native version on cocopods seems to only be 5.3.1? 

Please help to fix this issue and God please test your sdk(s) before release it!!!

**Comment by armnotstrong** [comment]
the above trying got no luck ...

**Comment by RicardoBusta** [comment]
Having exactly the same issue right now. We created packages for the new Unity package system, and depending on the solution, this conflict might create some weird dependencies between our facebook packages.

Facebook 7.17.1 and FAN 5.2.0

**Comment by Apoll0** [comment]
Tested today:
new Facebook SDK 7.17.2 + old FAN 5.2 - Working! (don't forget Xcode linker flag -lxml2)
new Facebook SDK 7.17.2 + new FAN 5.4.1 - new error, can't fix

So, stopped at 7.17.2 + 5.2

**Comment by armnotstrong** [comment]
Thanks for your reply @Apoll0 , but we are looking for a major bug fix claimed to be shipped with version 5.4.1,  So we are counting on FB guys fix this right ASAP.

**Comment by RicardoBusta** [comment]
Updated to 7.17.2 and it worked as well. Thanks @Apoll0 !

**Comment by armnotstrong** [comment]
@RicardoBusta 
Tested today:
new Facebook SDK 7.17.2 + new FAN 5.4.1   do not work.

"ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/dev/Desktop/test-fb/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: Linking globals named 'fbad_Cocos2DGetGLViewController': symbol multiply defined! for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by RicardoBusta** [comment]
@armnotstrong try using FAN 5.2 + SDK 7.17.2
Worked for iOS and Android here.

**Comment by luizjunior** [comment]
> @RicardoBusta
> Tested today:
> new Facebook SDK 7.17.2 + new FAN 5.4.1 do not work.
> 
> "ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/dev/Desktop/test-fb/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
> ld: Linking globals named 'fbad_Cocos2DGetGLViewController': symbol multiply defined! for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)"

same problem here.

**Comment by armnotstrong** [comment]
@RicardoBusta  I need upgrade to Audience network to 5.4.1 ,becouse the new  version  fix some serious bug .

**Comment by gfaraj** [comment]
Any updates here? I'm getting the same duplicate symbol errors with FB 7.16.1 and FBAN 5.4.1. Trying now to upgrade to 7.17.2.

**Comment by gfaraj** [comment]
Nope, that still has 1 duplicate (they were like 8 before, so an improvement). I guess I'll have to downgrade to 5.2, but I can't find where to download older versions. Can someone point to it?

**Comment by luizjunior** [comment]
> Nope, that still has 1 duplicate (they were like 8 before, so an improvement). I guess I'll have to downgrade to 5.2, but I can't find where to download older versions. Can someone point to it?

https://origincache.facebook.com/developers/resources/?id=audience-network-unity-sdk-5.2.0.zip

**Comment by gfaraj** [comment]
Thanks @luizjunior

**Comment by USPTech** [comment]
> > @RicardoBusta
> > Tested today:
> > new Facebook SDK 7.17.2 + new FAN 5.4.1 do not work.
> > "ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/dev/Desktop/test-fb/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
> > ld: Linking globals named 'fbad_Cocos2DGetGLViewController': symbol multiply defined! for architecture arm64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)"
> 
> same problem here.

We're getting the same error.

FAN 5.2 causes a duplicate error with AdMob on Android whereas FAN 5.4.1 causes a duplicate error on iOS. It's very frustrating. Could we have an update on this issue?

**Comment by armnotstrong** [comment]
Any updates here?

**Comment by WTF-Grinch** [comment]
any news ? ? ? ? anyone ? anywhere ? :D

**Comment by JmyW** [comment]
Anyone got fix? I got same issue when I upgrade from 5.2.0 to 5.4.1 today.

**Comment by Jazzgazer** [comment]
I'm using only Facebook Audience Network 5.4.1. 
same problem is occured in xcode. 

I guess Facebook SDK is not reason because I'm don't import Facebook SDK yet. 

Please fix this issue!!

**Comment by jblong0717** [comment]
We're getting the same error.
new Facebook SDK 7.17.2 + new FAN 5.4.1 do not work.

any updates?

**Comment by tbredon** [comment]
hello, got same issue with Facebook SDK Unity 7.12.2 + Audience Network Sdk Unity 5.4.1.

I finnaly got this working by removing "Plugins/Editor" folder.

Hope this help

**Comment by tbredon** [comment]
Same error.
![image](https://user-images.githubusercontent.com/2014086/64239667-ed517900-cf00-11e9-9f2c-fc50d0d5cd60.png)

I have tested on a simple unity project with only Facebook Audience Network SDK 5.4.1.
The error occured only when linking with -ObjC flag.

Facebook SDK 7.17.2 is autiomatically adding this   flag to xcode project( in PostProcess step).
That's why the combinaison of FB Sdk and FAN Sdk trigger this error.
(So a workaround is to remove -ObjC flag but this may lead to other problems ? )

####
@FACEBOOK-TEAM could you please fix Audience Network SDK (FBAdBridgeCommon.mm) to be complient with -ObjC flag 
####

Thank you

**Comment by aaronhoogstraten** [comment]
I wonder if it would be possible to remove the wrapped iOS framework in the FAN Unity 5.4.1 SDK? My project is using App Lovin as a mediator which creates a Dependencies.xml file:
```
<?xml version="1.0" encoding="utf-8"?>
<dependencies>
    <androidPackages>
        <androidPackage spec="com.applovin.mediation:facebook-adapter:5.5.0.0" />
        <androidPackage spec="com.android.support:recyclerview-v7:28.+" />
        <androidPackage spec="com.android.support:appcompat-v7:28.+" />
    </androidPackages>
    <iosPods>
        <iosPod name="AppLovinMediationFacebookAdapter" version="5.5.0.0" />
    </iosPods>
</dependencies>
```
This file is used by https://github.com/googlesamples/unity-jar-resolver to add Cocoapods dependencies at build time. 
Using this method my project successfully builds and runs with FB Unity sdk 17.7.2 + FAN native iOS 5.5.0.

**Comment by umairh2018** [comment]
Any findings???

**Comment by tbredon** [comment]
the problem come from AudienceNetworkSdk which failed to link when using -ObjC flag.
i have open a bug on facebook developer but still waiting to be resolved: https://developers.facebook.com/support/bugs/508036486408059/

( a  dirty workaround is to remove this linker flag under xcode (facebook sdk is adding it in post processing steps)

**Comment by umairh2018** [comment]
It didn't resolve my case, I am still having this issue

**Comment by umairh2018** [comment]
Can you guide me how to resolve it...

**Comment by dsagi-presspo** [comment]
Also happens with FAN 5.5.
I can remove the Objc flag, but won't it cause other problems?

> the problem come from AudienceNetworkSdk which failed to link when using -ObjC flag.
> i have open a bug on facebook developer but still waiting to be resolved: https://developers.facebook.com/support/bugs/508036486408059/
> 
> ( a dirty workaround is to remove this linker flag under xcode (facebook sdk is adding it in post processing steps)

**Comment by umairh2018** [comment]
From where you delete the obj c .

**Comment by umairh2018** [comment]
Yes. Its causing other issues like fbsdk not present. Something like that

**Comment by 1100111111** [comment]
For those that have frameworks requiring static linking, but where -ObjC isn't an option due to the Facebook glitch,I found that it can help to use the -force_load as mentioned here:

https://stackoverflow.com/questions/31580245/how-to-link-the-library-with-force-load-in-xcode

**Comment by asadmehar** [comment]
> For those that have frameworks requiring static linking, but where -ObjC isn't an option due to the Facebook glitch, I found that it can help to use -force_load as mentioned here:
> 
> https://stackoverflow.com/questions/31580245/how-to-link-the-library-with-force-load-in-xcode

Its not working for me. I have this error with AdMob and Facebook audience network 
Linking globals named 'fbad_Cocos2DGetGLViewController': symbol multiply defined! for architecture arm64

**Comment by umairh2018** [comment]
Same issue with me...

**Comment by jounisuom** [comment]
I created an empty Unity project. I did nothing else than switched to iOS platform, imported FB Unity SDK 7.17.2 and FB Audience Network Unity SDK 5.5.1 and I get the same error while building:
Linking globals named 'fbad_Cocos2DGetGLViewController': symbol multiply defined! for architecture arm64

**Comment by sebneo** [comment]
There are instructions here on managing the conflict, has anyone tried it?
https://developers.facebook.com/docs/audience-network/changelog-unity#5_4_1

**Comment by WTF-Grinch** [comment]
the funny fact :) i posted this problem on 18 of august and still they manage to push 2-3 updates and dont even look at bug-crash coments and issue :) thumbs up for idiots at SDK Team 👍

**Comment by zenith-jacob** [comment]
Any news on this disaster?

**Comment by umairh2018** [comment]
No update. still facing the issue...

**Comment by Mr-ZeroX** [comment]
Still

**Comment by KylinChang** [comment]
Hi all, FB AN SDK v5.6.0 is released and it's using Cocoapods/Maven to pull the latest SDK as FB Unity SDK, it should work with FB Unity SDK v7.18.0 now. I suggest reporting a bug in https://developers.facebook.com/bugs/ so that we can react more quickly. Close the issue, feel free to open the issue if the problem still exists.

**Comment by insthync** [comment]
<img width="1080" alt="Screen Shot 2562-11-08 at 06 17 57" src="https://user-images.githubusercontent.com/2697550/68436327-47680680-01f0-11ea-9bb7-8e88f34adf32.png">

Issues when build with FAN 5.6.0, the SDK added to Podfile, Already did pod install, but can't build.

**Comment by armnotstrong** [comment]
@insthync exactly the same error, did you find a solution?

**Comment by armnotstrong** [comment]
@insthync it seems that the newest FAN has removed support for native ads, so you should remove all the AudienceNetwork folder and reimport the SDK to solve this, good luck

**Comment by insthync** [comment]
I can fix it by close Unity, then remove Library folder from my project folder then open Unity and build it, now all errors gone.

**Comment by dsagi-presspo** [comment]
I'm now unable to build for Android. It seems that the iOS build and run works fine.

Using Android Resolver adds the new dependencies:
<androidPackage spec="com.android.support:support-annotations:28.0.0" />
<androidPackage spec="com.facebook.android:audience-network-sdk:5.6+" />

I first suspected the support dependency, since I am using "Use Jetifier" option. Removing it didn't help. I tried removing the fan dependency (just for testing, I knew this isn't the right way) and the build succeeded. However (and like expected), the app crashed while running.
Not sure how to continue from here.

Here are the messages I get, I can't see any helpful info:
Execution failed for task ':transformClassesWithMultidexlistForDebug'.
com.android.build.api.transform.TransformException: Error while generating the main dex list.

exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <563f4bbc342a4b6b88ae70c46cea610c>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:281)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by gboswood-hookbang** [comment]
> I can fix it by close Unity, then remove Library folder from my project folder then open Unity and build it, now all errors gone.

Thank you!  This worked for me after trying a large number of other suggestions online and losing way too much time on this.  For the record, I'm using Unity 2019.3.10f1, Facebook SDK 17.7.2, and I don't think it matters but Xcode 11.4.1.
