### ISSUE TITLE
7.17.2 Android app crash on launch due to ClassNotFoundException for "com.facebook.FacebookContentProvider"

### ISSUE THREAD

**Issue by aaronhoogstraten** [facebook/facebook-sdk-for-unity#294]
Here is the exception in the android log on launch:

> 07-24 14:42:27.028: E/AndroidRuntime(30504): java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.playq.ckdevelop-nH7Sn1oGSGgK_7rBa9gvxQ==/base.apk"],nativeLibraryDirectories=[/data/app/net.playq.ckdevelop-nH7Sn1oGSGgK_7rBa9gvxQ==/lib/arm, /data/app/net.playq.ckdevelop-nH7Sn1oGSGgK_7rBa9gvxQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]

We're using GooglePlayResolver v1.2.122.0 which seems to import all the necessary Facebook libraries including `facebook-core.5.1.1`. 
The SDK adds the following to my AndroidManifest:
>     <meta-data android:name="com.facebook.sdk.AutoLogAppEventsEnabled" android:value="true" />
>     <meta-data android:name="com.facebook.sdk.AdvertiserIDCollectionEnabled" android:value="true" />
>     <activity android:name="com.facebook.unity.FBUnityLoginActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
>     <activity android:name="com.facebook.unity.FBUnityDialogsActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
>     <activity android:name="com.facebook.unity.FBUnityAppLinkActivity" android:exported="true" />
>     <activity android:name="com.facebook.unity.FBUnityDeepLinkingActivity" android:exported="true" />
>     <activity android:name="com.facebook.unity.FBUnityGameRequestActivity" />
>     <activity android:name="com.facebook.unity.FBUnityCreateGameGroupActivity" />
>     <activity android:name="com.facebook.unity.FBUnityJoinGameGroupActivity" />
>     <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="fb*correct app ID*" />
>     <provider android:name="com.facebook.FacebookContentProvider" android:authorities="com.facebook.app.FacebookContentProvider*correct app ID*" android:exported="true" />

We were using a very old version of the SDK (7.9.0), but have just updated to 7.17.2 at the same time as moving from Unity 5.6.3 to Unity 2019.1.9f1. I made sure to first delete the old FacebookSDK from the project before importing the new 7.17.2 package.

**Comment by KylinChang** [comment]
Hey @aaronhoogstraten ,  can you try adding `-keep class com.facebook.internal.* {*;}` and `-keep class com.facebook.* {*;}` in your proguard file?

**Comment by aaronhoogstraten** [comment]
@KylinChang Yup this was indeed the issue (along with a plethora of other libraries for our other plugins), cheers!

**Comment by phatsngoo2702** [comment]
@KylinChang Your solution not work for me :( add it to Proguard file but still receiving this error :
"java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/data/app/com.scopely.fortunecookie-ZJA4FcXkhu1nSuq6l5uzoQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.scopely.fortunecookie-ZJA4FcXkhu1nSuq6l5uzoQ==/lib/arm64, /data/app/com.scopely.fortunecookie-ZJA4FcXkhu1nSuq6l5uzoQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]"

**Comment by KylinChang** [comment]
Hey @phatsngoo2702 , did you add `-keep class com.facebook.* {*;}`? If you added it, can you share a sample project to me?

**Comment by jkampitakis** [comment]
Same problem here..

Added
-keep class com.facebook.internal.* {*;}
-keep class com.facebook.* {*;}

to proguard-user.txt


09-03 18:32:53.077 19401 19401 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/lib/arm64, /data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6590)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6115)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/lib/arm64, /data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6574)
09-03 18:32:53.077 19401 19401 E AndroidRuntime: 	... 10 more
09-03 18:33:16.584 19520 19520 E AndroidRuntime: FATAL EXCEPTION: main
09-03 18:33:16.584 19520 19520 E AndroidRuntime: Process: com.lazyland.skylandsaga, PID: 19520
09-03 18:33:16.584 19520 19520 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/lib/arm64, /data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6590)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6115)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/lib/arm64, /data/app/com.lazyland.skylandsaga-lx5TVW7M5IXheo4K1QmYgQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6574)
09-03 18:33:16.584 19520 19520 E AndroidRuntime: 	... 10 more

**Comment by KylinChang** [comment]
Hey @jkampitakis , is it possible for you to upload a sample project to me?

**Comment by uerceg** [comment]
Hi @KylinChang 

Here you go: [InstallReferrerUnity.zip](https://github.com/facebook/facebook-sdk-for-unity/files/4641386/InstallReferrerUnity.zip)

Cheers

**Comment by AnthonyDemanueleFSG** [comment]
Another sample project here @KylinChang 
[FSGTestAppMinProj.zip](https://github.com/facebook/facebook-sdk-for-unity/files/5210656/FSGTestAppMinProj.zip)

I've posted more detailed info here but I got no reply/success yet.

Thank you.

**Comment by alexey-kruchenok** [comment]
any uptade on this? also have problems on empty project with FB SDK

**Comment by LukaFarkas98** [comment]
Having same problem, application crashes when launched. Hope someone will find a fix

**Comment by juliodutra2003** [comment]
same problem here.
Unity 2019.4.18
Facebook SDK 9.0.0

**Comment by incredible100rav** [comment]
Same problem 
Unity 2019.2.17
Facebook SDK 9.0.0

**Comment by AliRehman7141** [comment]
I have the same problem in react-native app
https://github.com/facebook/react-native/issues/30828
