### ISSUE TITLE
Facebook Unity 7.1.0

### ISSUE THREAD

**Issue by leopripos** [facebook/facebook-sdk-for-unity#3]
I copy code from https://developers.facebook.com/docs/unity/examples
But it show 2 errors:

> You cannot show two modal windows at once
UnityEngine.GUI:ModalWindow(Int32, Rect, WindowFunction, String)
Facebook.Unity.Editor.EditorFacebookMockDialog:OnGUI() (at Assets/Facebook/Scripts/PlatformEditor/EditorFacebookMockDialog.cs:47)

and..

> ArgumentException: Getting control 0's position in a group with only 0 controls when doing Repaint
Aborting
UnityEngine.GUILayoutGroup.GetNext () (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:637)
UnityEngine.GUILayoutUtility.DoGetRect (Single minWidth, Single maxWidth, Single minHeight, Single maxHeight, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:382)
UnityEngine.GUILayoutUtility.GetRect (Single width, Single height, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:356)
UnityEngine.GUILayout.Space (Single pixels) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayout.cs:247)
Facebook.Unity.Editor.EditorFacebookMockDialog.OnGUIDialog (Int32 windowId) (at Assets/Facebook/Scripts/PlatformEditor/EditorFacebookMockDialog.cs:84)
UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUI.cs:1804)

**Comment by swiese** [comment]
Thanks for bringing this to our attention. You are probably showing either two of our dialogs at once or your own dialog and one of our dialogs at the same time. To fix this you can just change one line in the Facebook SDK to create a Window instead of a ModalWindow at
https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Assets/Facebook/Scripts/PlatformEditor/EditorFacebookMockDialog.cs#L47

We will look to fix this in our next release.

For more info see the stackoverflow post on this issue
http://stackoverflow.com/questions/31297578/two-modal-windows-facebook

**Comment by ArmandCloud** [comment]
Hello,
Link are broken since its and old issue. 
I have the same problem when testing invitation in editor, with SDK 7.9 .
I think this workaround is outdated now since sdk has no .cs files.
Best Regards,
