### ISSUE TITLE
Invalid Scopes: user_friends

### ISSUE THREAD

**Issue by birdkingz** [facebook/facebook-sdk-for-unity#390]
May I know why am I getting this during login?
Because of this, I can't proceed to test the FB integration due to the login rejection by this error.

Please help.

**Comment by kultie** [comment]
I think that you might request login with "user_friends" scope but the application on facebook at section "Permission and Feature" you didn't enable the "user_friends" permission. This error only show to the developers and administrator. So there're 3 ways to continue to use facebook is
- Remove scope "user_friends" of facebook login in unity
- Add the "user_friends" permission on https://developers.facebook.com/apps/[your app id]/app-review/permissions/
- Add a tester at https://developers.facebook.com/apps/[your app id]/roles/roles/

**Comment by birdkingz** [comment]
I contacted FB support and they told me it was because user_friends permission isn't approved which is why I'm not allowed to use it in LIVE app.

**Comment by fmoyano** [comment]
I've been struggling with this for weeks now.

The thing is the following: my app is in Live mode, and I want to get the user_friends permission accepted by Facebook. I've sent the app several times to Review and I always get this permission rejected because they are unable to test it.

I have tried to get the user_friends permission to work by using a Test App with Test Users granting them the user_friends permission. However, when I test it on the device logged as these test users, the permission is ignored (I only get the public_profile and the email permissions).

I don't know if the problem is that the Facebook Login is completed through Firebase Auth, and the latter is configured to work with the app in Live (not the test app). However I cannot change this configuration because otherwise the players would be unable to login with the version published on the store.

What am I missing? It's exasperating and the review feedback from Facebook is completely helpless.

**Comment by danyalahmed1995** [comment]
First you need to make sure facebook business account is verified under **Review --> Verification**, next you want to fill out contact details and data deletion instructions url under **App Settings --> Basic Settings**, Also in use cases add the **(gaming_profile, gaming_user_picture) and (user_friends)** for your invalid scope error prompt screen , which only happens if you are the admin of the app you need to add those permission in the code

**{ "gaming_profile", "user_friends" }**

Hope that helps
