### ISSUE TITLE
SDK v13.2 graph APIs always returns HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by majidkh** [facebook/facebook-sdk-for-unity#617]
## Checklist

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: `2021.3.4f1`
- Unity SDK Version: `13.2.0`
- Installation Platform & Verison: `Mac OSX on M1 Mac` version `Monterey`

## Goals

Login to Facebook using the Facebook Example .

## Expected Results

result.Error should be empty but gives the following error:

6/10/2022 04:58:54 pm
Facebook.Unity.LoginResult
LoginResult:
	Error: Graph API error: HTTP/1.1 400 Bad Request
	RawResult: {"error":"Graph API error: HTTP/1.1 400 Bad Request","callback_id":"2"}
	Cancelled: False
LoginResult:
	AccessToken: null
	AuthenticationToken: null

6/10/2022 04:58:45 pm
OnInitCompleteCalled IsLoggedIn='False' IsInitialized='True'

Updated from Facebook SDK 12 to 13.2 with exact same specs ( It works fine with SDK 12 ).

## Steps to Reproduce

Run the Example MainMenu scene from Facebook SDK and click on the Init and then try to login. Then check the error logs.

## Code Samples & Details

Same codes as in Examples in the SDK

**Note:** Remember to format your code for readability:

```java
// INSERT YOUR CODE HERE
```

**Comment by snorrsi** [comment]
@majidkh did you set the Client Token in Facebook settings in Unity? It´s required from Facebook SDK 13+

**Comment by majidkh** [comment]
@snorrsi Yes, added both in Facebook Settings and manually added to the AndroidManifest.xml file too, and still the same,

It doesn't work with neither Editor or Android build. any hints?

**Comment by gtalwadkar** [comment]
Facing same issue. Seems like issue is SDK 13.2.0 pointing to Graph API v13.2 instead of v13.0.

**Comment by LinuleX** [comment]
+1 Exact same issue.... Unity SDK v13.2.0 on M1 Mac

**Comment by majidkh** [comment]
I can confirm this issue is now fixed, just cloned the latest version and built it and all works well now, I will be closing this issue now.

**Comment by LinuleX** [comment]
Is it possible to share the unitypackage that you've build? Because I cloned the latest version but unable to built since you've closed this issue. (4 hrs)

**Comment by mrcooper** [comment]
Today I downloaded latest SDK release (which is facebook-unity-sdk-13.2.0.zip from [Jun 6, 2022](https://developers.facebook.com/docs/unity/downloads)) and facing same issue. 

Seems it isn't fixed in library:
<img width="571" alt="2022-06-21_11-15-39" src="https://user-images.githubusercontent.com/2012650/174751050-d2a50671-b295-4063-ad25-4bada739962d.png">

Only when I manually call 
` FB.GraphApiVersion = "v13.0";`
the error gone

**Comment by LinuleX** [comment]
Hello,

I temporarly fixed the issue by adding the line below just after fb sdk  init and activate app on unity

FB. GraphApiVersion ="v14.0";

Regards


Sent from my iPhone

On 21 Jun 2022, at 11:19, Roman Ivankov ***@***.***> wrote:

﻿

Today I downloaded latest SDK release (which is facebook-unity-sdk-13.2.0.zip from Jun 6, 2022<https://developers.facebook.com/docs/unity/downloads>) and facing same issue.

Seems it isn't fixed in library:
[2022-06-21_11-15-39]<https://user-images.githubusercontent.com/2012650/174751050-d2a50671-b295-4063-ad25-4bada739962d.png>

Only when I manually call
FB.GraphApiVersion = "v13.0";
the error gone
