### ISSUE TITLE
Unity Gradle build throws an error: HardcodedDebugMode

### ISSUE THREAD

**Issue by takaaptech** [facebook/facebook-sdk-for-unity#64]
Today, I try to build my unity project (include FB sdk 7.9.0) by using Gradle build feature on android Build Setting / Build System.
And Gradle throws an error: HardcodedDebugMode (More info see bellow)

After Searching all my Plugins, I see it in DefaultAndroidManifest.xml.
And if i remove FB sdk, build works.

So i think this is maybe our bug?

Thanks!

Error: Avoid hardcoding the debug mode; leaving it out allows debug and release builds to automatically assign one [HardcodedDebugMode]
  <application android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="false" android:isGame="true" android:banner="@drawable/app_banner">
Explanation for issues of type "HardcodedDebugMode":
   It's best to leave out the android:debuggable attribute from the manifest.
   If you do, then the tools will automatically insert android:debuggable=true
   when building an APK to debug on an emulator or device. And when you
   perform a release build, such as Exporting APK, it will automatically set
   it to false.

**Comment by takaaptech** [comment]
I am sorry, The error comes when combine FB sdk with GoogleMobileAdsPlugin.
GoogleMobileAdsPlugin or FB sdk standalone do not error.
It seems that unity try to merge manifest from both plugin so that cause the error.

**Comment by takaaptech** [comment]
Anyone have the solution (workaround) for this?

**Comment by bdominguez** [comment]
In my case the problem was with GoogleAnalytics Unity package.

Facebook has many support libraries on v23 and GoogleAnalytics on v24.

So my Unity project had many AAR packages that were the same but duplicated on different versions.

I had to solve this manually:

- Remove v23 packages from Facebook plugin.
- Copy them from my Android SDK path on v24 to match other GoogleAnalytics AAR packages that were already there.

It seems like it's related to #42

**Comment by takaaptech** [comment]
Thank @bdominguez ! I resolve it by remove:
- support-annotations-24.0.0 
- support-v4-24.0.0.aar in folder Assets\FacebookSDK\Plugins\Android\libs
