### ISSUE TITLE
FB.LogPurchase problems with CultureInfo

### ISSUE THREAD

**Issue by danielsb** [facebook/facebook-sdk-for-unity#75]
I'm currently having an issue when trying to call `FB.LogPurchase`. Depending on the `CultureInfo` of the device, you may have problems to log the price.

If I call the `FB.LogPurchase` and my CultureInfo is set to a culture that use comma `,` as a decimal separator, FB fails to parse that later on in the Android native code ([`FB.java` line 219](https://github.com/facebook/facebook-sdk-for-unity/blob/dev/facebook-android-wrapper/src/com/facebook/unity/FB.java#L219)).
The workaround I found is to set the `CurrentCulture` to `CultureInfo.InvariantCulture` before calling the `FB.LogPurchase`.

Is that a known issue or am I missing any kind of configuration for that?

**Comment by zarkov** [comment]
**+1**
I have exactly the same issue.

Hi, @danielsb could you please tell me how did you change the `CurrentCulture` on your side ?
I did the following and seems to work on my side:
`System.Globalization.CultureInfo oldCulture = System.Threading.Thread.CurrentThread.CurrentCulture;`
`System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;`
`FB.LogPurchase(item.LocalizedPrice, item.IsoCurrencyCode, iapParameters);`
`System.Threading.Thread.CurrentThread.CurrentCulture = oldCulture;`

Thanks for the workaround.

**Comment by danielsb** [comment]
Hi @zarkov, yeah we're basically doing the very same thing. I don't like it, but it's the only way I found without modifying the native code.

**Comment by zarkov** [comment]
Yeah @danielsb, it is quite mind boggling that an analytic that is quite important has this big of a flaw.
Hope they fix it soon.

**Comment by giliwerner** [comment]
We are seeing the exact same issue...
We change the CultureInfo according to the language the user plays in, and if the delimiter is a comma we see the exception:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.facebook.unity.UnityParams.has(java.lang.String)' on a null object reference

Why hasn't this been fixed since 2017...?
It should be such a simple fix for Facebook... Just calling the toString function with CultureInfo.InvariantCulture should do the trick...

**Comment by KylinChang** [comment]
Hi all, thanks for the report. The issue will be fixed in the next release

**Comment by KylinChang** [comment]
The issue should be fixed in v7.16.0
