### ISSUE TITLE
OGActionType parameter should be nullable, but is not.

### ISSUE THREAD

**Issue by Whyser** [facebook/facebook-sdk-for-unity#8]
`OGActionType` parameter should be nullable, but it is not.

See: https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Assets/Facebook/Scripts/FB.cs#L281

It should be `OGActionType?`. Otherwise the method `ValidateAppRequestArgs(..., OGActionType? actionType, ...)` in FacebookBase.cs doesn't make sense.

**Comment by swiese** [comment]
The validateAppRequestArgs is used to validate the inputs from the multiple app request methods on FB. If it was not nullable you could not validate the value from 
https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Assets/Facebook/Scripts/FB.cs#L363

Additionally it should not be nullable since you can't have an AppRequest with an og object but no action type.

**Comment by Whyser** [comment]
Ahh sorry, I missed that it was being used elsewhere!

The reason I even stumbled upon this, is because if I send a `OGActionType.SEND` and then have `objectId = ""` it will throw an error (on Android at least). But if I pass `OGActionType = null`, it will actually work.

Maybe some logics with the !string.IsNullOrEmpty got messed up? (Can't try it out since I'm not at work any more)
